import time
import json
import random
from kafka import KafkaProducer

# Configuration
KAFKA_BROKER = 'localhost:9092'
TOPIC = 'logistics_events'

def generate_event():
    locations = ["Rotterdam", "Hamburg", "Antwerp", "Valencia", "Piraeus"]
    statuses = ["on_time", "delayed", "customs_hold", "arrived"]
    
    return {
        "shipment_id": f"SHP-{random.randint(1000, 9999)}",
        "location": random.choice(locations),
        "status": random.choice(statuses),
        "timestamp": time.time(),
        "meta": "Mock event generated by eco-producer"
    }

def main():
    print(f"Connecting to Kafka at {KAFKA_BROKER}...")
    producer = None
    retries = 5
    
    while retries > 0:
        try:
            producer = KafkaProducer(
                bootstrap_servers=[KAFKA_BROKER],
                value_serializer=lambda x: json.dumps(x).encode('utf-8')
            )
            print("Connected to Kafka!")
            break
        except Exception as e:
            print(f"Connection failed ({e}). Retrying in 5s...")
            time.sleep(5)
            retries -= 1

    if not producer:
        print("Failed to connect to Kafka. Exiting.")
        return

    print(f"Starting event stream to topic '{TOPIC}'...")
    try:
        while True:
            event = generate_event()
            producer.send(TOPIC, value=event)
            print(f"Sent: {event}")
            time.sleep(2) # Send one event every 2 seconds
    except KeyboardInterrupt:
        print("Stopping producer.")
        producer.close()

if __name__ == "__main__":
    main()
